version: "3.8" # Specify the Docker Compose file version

services:
  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    ports:
      - "7077:7077"
    networks:
      - mynetwork

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - mynetwork

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork: # Define the custom network

