services:
  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    ports:
      - "7077:7077"
    networks:
      - mynetwork
    env_file:
      - .env

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - mynetwork
    volumes:
      - wordpress-data:/var/www/html
    env_file:
      - .env

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - mynetwork
    volumes:
      - wordpress-data:/var/www/html
    env_file:
      - .env

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env

networks:
  mynetwork: # Define the custom network

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: "none"
      o: bind
      device: "~/bpisak-l/data/wp"
  db-data:
    driver: local
    driver_opts:
      type: "none"
      o: bind
      device: "~/bpisak-l/data/db"
