services:
  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    ports:
      - "7077:7077"
    networks:
      - mynetwork
    env_file:
      - .env
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - mynetwork
    volumes:
      - wordpress-data:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        DOMAIN: ${DOMAIN}
        LOGIN: ${LOGIN}
        CERTIFICATE: ${CERTIFICATE}
        KEY: ${KEY}
    ports:
      - "443:443"
    networks:
      - mynetwork
    volumes:
      - wordpress-data:/var/www/html
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: on-failure

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env
    restart: on-failure

networks:
  mynetwork: # Define the custom network

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: "none"
      o: bind
      device: "~/bpisak-l/data/wp"
  db-data:
    driver: local
    driver_opts:
      type: "none"
      o: bind
      device: "~/bpisak-l/data/db"
