version: "3.8" # Specify the Docker Compose file version

services:
  adminer: # First service/container
    image: adminer # Replace with your actual app image name
    ports:
      - "9000:9000" # Map port 9000 of the container to port 9000 on the host
    networks:
      - mynetwork # Connect to the custom network

  nginx: # Second service/container
    image: nginx # Replace with your actual database image name
    networks:
      - mynetwork # Connect to the same custom network

networks:
  mynetwork: # Define the custom network
